-- MySQL Script generated by MySQL Workbench
-- Thu Sep  3 10:17:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema neusamoda_db
-- -----------------------------------------------------
-- Inicialização da integração entre o backend e o banco de dados.

-- -----------------------------------------------------
-- Schema neusamoda_db
--
-- Inicialização da integração entre o backend e o banco de dados.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `neusamoda_db` DEFAULT CHARACTER SET utf8 ;
USE `neusamoda_db` ;

-- -----------------------------------------------------
-- Table `neusamoda_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`usuarios` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(12) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `permissao` TINYINT(1) NOT NULL COMMENT '0->vendedor\n1->adm',
  `ativo` TINYINT(1) NOT NULL COMMENT '0 - ATIVO\n1 - INATIVO',
  `dataAtiv` DATE NULL,
  `dataDes` DATE NULL,
  `cpf` VARCHAR(11) NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`categorias` (
  `id` TINYINT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NULL,
  `dsc` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`fornecedores` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NULL,
  `tel` BIGINT(14) NULL,
  `obs` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `vlrVenda` DECIMAL(7,2) UNSIGNED NOT NULL,
  `dsc` TEXT NULL,
  `status` TINYINT(1) NULL COMMENT '0 - ATIVO\n1 - INATIVO',
  `cor` VARCHAR(30) NULL,
  `genero` VARCHAR(30) NULL,
  `dataCompra` DATE NULL,
  `dataVenda` DATE NULL,
  `qtde` INT NULL,
  `estilo` VARCHAR(45) NULL,
  `imagem` BLOB NULL,
  `tam` CHAR(4) NULL,
  `vlrPago` DECIMAL(7,2) NULL,
  `colecao` VARCHAR(45) NULL,
  `code` VARCHAR(13) NULL,
  `categorias_id` TINYINT ZEROFILL NOT NULL,
  `fornecedores_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categorias_idx` (`categorias_id` ASC),
  INDEX `fk_produtos_fornecedores1_idx` (`fornecedores_id` ASC),
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `neusamoda_db`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_fornecedores1`
    FOREIGN KEY (`fornecedores_id`)
    REFERENCES `neusamoda_db`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`clientes` (
  `id` SMALLINT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  `dataNascimento` DATE NULL,
  `email` VARCHAR(100) NULL,
  `fone` BIGINT(14) NULL,
  `celular` BIGINT(14) NULL,
  `rg` VARCHAR(20) NULL,
  `end` VARCHAR(100) NULL,
  `dataRegistro` DATE NOT NULL,
  `dsc` TEXT NULL,
  `credito` TINYINT(1) NULL COMMENT '0 <- quite\n1 <- devedor',
  `tam` VARCHAR(10) NULL,
  `medida` INT NULL,
  `refer` VARCHAR(45) NULL,
  `filiacao` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`vendas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vlrTotal` DECIMAL(7,2) NOT NULL,
  `data` DATETIME NOT NULL,
  `dsc` DECIMAL(7,2) NULL,
  `metPgto` INT NULL COMMENT '0->a vista\n1->parcelado',
  `frmPgto` SMALLINT NULL COMMENT 'O->dinheiro\n1-> cartao de crédito\n2->cartão de débito\n3->cheque\n4->crediario\n5->Depósito/Transferência',
  `vlrPago` DECIMAL(7,2) NULL COMMENT 'valor quitado (caso parcelado)',
  `qtdeParc` TINYINT NULL COMMENT 'quantidade de parcelas',
  `clientes_id` SMALLINT ZEROFILL UNSIGNED NOT NULL,
  `produtos` TEXT NULL,
  `usuarios_id` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_clientes1_idx` (`clientes_id` ASC),
  INDEX `fk_vendas_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `neusamoda_db`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `neusamoda_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`despesas` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL NOT NULL,
  `data` DATETIME NOT NULL,
  `dsc` TEXT NOT NULL,
  `usuarios_id` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_despesas_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_despesas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `neusamoda_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`pagamentos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vlr` DECIMAL(7,2) NOT NULL,
  `data` DATE NOT NULL,
  `obs` TEXT NULL,
  `vendas_id` INT UNSIGNED NOT NULL,
  `frmPgto` TINYINT(1) NULL COMMENT 'O->dinheiro\n1-> cartao de crédito\n2->cartão de débito\n3->cheque\n4->crediario\n5->Depósito/transferência',
  PRIMARY KEY (`id`),
  INDEX `fk_pagamentos_vendas1_idx` (`vendas_id` ASC),
  CONSTRAINT `fk_pagamentos_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `neusamoda_db`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neusamoda_db`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neusamoda_db`.`caixa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vlr` DECIMAL(7,2) NOT NULL,
  `data` DATETIME NOT NULL,
  `obs` TEXT NULL,
  `tipo` TINYINT(1) NULL COMMENT '0-> entrada\n1->saida',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
